name       : python-hypothesis
version    : 3.44.4
release    : 1
source     :
    - https://github.com/HypothesisWorks/hypothesis-python/archive/3.44.4.tar.gz : f7c685ebc981d0332be184ebed9c45a954c9869441273412cabc37ae26fd13a6
license    : MPL-2.0
component  : programming.python
summary    : Advanced property-based (QuickCheck-like) testing for Python
description: |
    Hypothesis is an advanced testing library for Python. It lets you write tests which are parametrized by a source of examples, and then generates simple and comprehensible examples that make your tests fail. This lets you find more bugs in your code with less work.
builddeps  :
    - python-setuptools
rundeps    :
    - python-attrs
    - python-coverage
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
