name       : python-hypothesis
version    : 4.54.1
release    : 13
source     :
    - https://github.com/HypothesisWorks/hypothesis/archive/hypothesis-python-4.54.1.tar.gz : 04f3fe5d29d97abf58847416636f7b463608ce71d084cf3f879844a13e2e1c91
license    : MPL-2.0
component  : programming.python
summary    : Advanced property-based (QuickCheck-like) testing for Python
description: |
    Hypothesis is an advanced testing library for Python. It lets you write tests which are parametrized by a source of examples, and then generates simple and comprehensible examples that make your tests fail. This lets you find more bugs in your code with less work.
builddeps  :
    - numpy
    - python-coverage
    - python-enum34
    - python-flaky
    - python-mock
    - python-pexpect
    - python-pytest
    - python-pytz
    - python-setuptools
rundeps    :
    - python-attrs
    - python-coverage
    - python-enum34
setup      : |
    result=${PWD##*/}
    cp -a hypothesis-python ..
    cd .. && rm -fr $result
build      : |
    %python3_setup
install    : |
    %python3_install
# Take forever
#check      : |
#    %python3_test pytest3 -c /dev/null --assert=plain tests/py3 tests/cover tests/nocover tests/datetime tests/numpy
