name       : python-hypothesis
version    : 3.82.1
release    : 5
source     :
    - https://github.com/HypothesisWorks/hypothesis/archive/hypothesis-python-3.82.1.tar.gz : 021859ee1bd132b45dabd1d413c692f82601a8f11848174caaa43fdf3525e22e
license    : MPL-2.0
component  : programming.python
summary    : Advanced property-based (QuickCheck-like) testing for Python
description: |
    Hypothesis is an advanced testing library for Python. It lets you write tests which are parametrized by a source of examples, and then generates simple and comprehensible examples that make your tests fail. This lets you find more bugs in your code with less work.
builddeps  :
    - numpy
    - python-coverage
    - python-dateutil
    - python-enum34
    - python-flaky
    - python-mock
    - python-pytest
    - python-pytz
    - python-setuptools
rundeps    :
    - python-attrs
    - python-coverage
    - python-enum34
setup      : |
    result=${PWD##*/}
    cp -a hypothesis-python ..
    cd .. && rm -fr $result
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -c /dev/null --assert=plain tests/py2 tests/cover tests/nocover tests/datetime tests/numpy
    %python3_test py.test3 -c /dev/null --assert=plain tests/py3 tests/cover tests/nocover tests/datetime tests/numpy
